"""Conversation engine for POST /v1/reply.

    classify_inbound()     deterministic, ordered intent rules (English, Hinglish, Devanagari Hindi)
    parse_wait_seconds()   "tomorrow" -> 86400, "in 2 hours" -> 7200, "busy" -> 1800
    ConversationEngine     handle_reply(req) -> {"action": "send" | "wait" | "end", ...}
                           open_from_action() registers a tick opener as a conversation

Moves are always decided in code, never by the LLM: auto-reply streaks (nudge, then wait,
then end), opt-out and hostility exits, waits, declines, ACTION MODE after a commitment,
slot confirmations, off-topic redirects and grounded answers. When an LLM is configured
and time allows, it only rewrites the body of the chosen move behind the validator;
otherwise (and whenever its output is rejected) app/reply_templates.py writes the body.
"""

from __future__ import annotations

import asyncio
import importlib
import itertools
import logging
import re
import time
import unicodedata
from dataclasses import dataclass, field
from datetime import timedelta
from typing import Any

from app import config
from app import reply_templates as rt
from app.numbers import extract_number_tokens, normalize_number
from app.schemas import (
    CTA_BINARY_CONFIRM,
    CTA_NONE,
    CTA_OPEN_ENDED,
    CTA_VALUES,
    SEND_AS_MERCHANT,
    SEND_AS_VERA,
    FactSheet,
    LanguagePlan,
)
from app.state import ContextStore, Conversation, ConversationStore, MerchantState, parse_iso, utc_now_iso

log = logging.getLogger(__name__)

# Global ordering of inbound turns across conversations (merchant-level auto-reply streaks).
_SEQ = itertools.count(1)

AUTO_REPLY_WAIT_S = 86400        # second auto-reply in a row: owner is not at the phone, come back tomorrow
DEFAULT_WAIT_S = 1800
MIN_WAIT_S = 300
MAX_WAIT_S = 30 * 86400
MAX_INBOUND_TURNS = 8            # keep conversations short (spec section 6)
MAX_BOT_TURNS_WITHOUT_PROGRESS = 4
REPLY_MARGIN_S = 0.6             # kept back from the reply deadline for validation + bookkeeping
MIN_LLM_S = 1.5                  # do not start an LLM call with less time than this
LLM_MAX_TOKENS = 700
TRANSCRIPT_TURNS = 8

# Moves whose body the LLM may rewrite. Short, exact moves (nudge, apology, confirmations,
# customer bookings) stay deterministic.
LLM_MOVES = {"action", "answer", "answer_action", "off_topic", "continue", "edit"}
# Opener kinds that asked the merchant a question: any substantive answer is engagement to act on.
ASK_KINDS = {"curious_ask_due", "scheduled_recurring", "active_planning_intent"}

REPLY_SCHEMA = {
    "type": "object",
    "properties": {"body": {"type": "string"}, "rationale": {"type": "string"}},
    "required": ["body"],
}


# --------------------------------------------------------------------------- normalisation


def normalize_text(text: Any) -> str:
    """Lower-case, drop apostrophes inside words ("let's" -> "lets"), strip punctuation and
    emoji, collapse spaces. Devanagari letters and vowel signs are kept."""
    if not isinstance(text, str) or not text:
        return ""
    s = unicodedata.normalize("NFKC", text).lower()
    s = re.sub(r"(?<=\w)['’`´](?=\w)", "", s)
    out = []
    for ch in s:
        cat = unicodedata.category(ch)
        out.append(ch if cat[0] in "LNM" else " ")
    return re.sub(r"\s+", " ", "".join(out)).strip()


_DV = "ऀ-ॿ"


def _dv(phrase: str) -> str:
    """Devanagari phrase with script-aware boundaries (\\b is unreliable around vowel signs)."""
    return rf"(?<![{_DV}]){phrase}(?![{_DV}])"


def _rx(*parts: str) -> re.Pattern:
    return re.compile("|".join(f"(?:{p})" for p in parts))


_POSITIVE_EMOJI = {"👍", "👌", "✅", "🙏", "💯", "🤝", "✔", "☑", "👏", "😊", "🙂", "😀", "😃", "❤", "🔥"}

# --------------------------------------------------------------------------- keyword sets

_AUTO_STRONG_RE = _rx(
    r"\bthank(?:s| you)(?: so much| very much)? for (?:contacting|reaching out|getting in touch|connecting with"
    r"|messaging|writing to|calling)\b",
    r"\b(?:our|the) (?:team|executive|staff|representative|agent|support team|customer care)s? (?:will|shall|would)"
    r" (?:respond|reply|get back|revert|contact|call|reach out|be in touch|assist)",
    r"\b(?:will|shall) (?:respond|reply|revert|get back to you)(?: to you)? (?:shortly|soon|at the earliest|asap"
    r"|as soon as (?:possible|we can)|within)\b",
    r"\brespond (?:to you )?shortly\b",
    r"\b(?:we|i) (?:have|ve) received your (?:message|query|enquiry|inquiry|request)\b",
    r"\b(?:automated|auto generated|autogenerated|automatic) (?:message|reply|response|assistant)\b",
    r"\bauto ?(?:reply|response|responder)\b",
    r"\bout of (?:the )?office\b",
    r"\b(?:outside|after) (?:our |the )?(?:business|working|office|opening) hours\b",
    r"\b(?:business|working|office|opening) hours (?:are|is)\b",
    r"\b(?:we are|we re|currently) (?:currently )?(?:closed|unavailable|away|not available)\b",
    r"\bthank you for your patience\b",
    r"\bmein aapka swagat hai\b",
    r"\bwelcome to\b.{0,80}\bhow (?:can|may) (?:we|i) help\b",
    r"\bteam tak pahu?ncha\w*",
    r"\bautomated assistant\b",
    r"\bmain ek (?:automated|auto)\b",
    r"\b(?:jald|jaldi) hi (?:aapse )?(?:sampark|baat|contact|jawab)\b",
    r"\bsampark karne ke liye (?:dhanyavad|dhanyawad|shukriya)\b",
    r"\baapka (?:sandesh|message) (?:mil gaya|prapt)\b",
    _dv("स्वचालित"), "संपर्क करने के लिए धन्यवाद", "आपका संदेश (?:प्राप्त|मिल)", "हम जल्द ही", "हमारी टीम",
)
_AUTO_WEAK_RE = _rx(
    r"\bthank(?:s| you)(?: so much| very much)? for (?:your (?:message|enquiry|inquiry|query|interest)|the message)\b",
    r"\bwe (?:will|shall|ll) get back to you\b",
    r"\bhow (?:can|may) (?:we|i) (?:help|assist) you\b",
    r"\bplease (?:leave|share|drop) (?:a |your )?(?:message|query|details)\b",
    r"\bjaa?nkari ke liye\b.{0,40}\b(?:shukriya|dhanyavad|dhanyawad)\b",
    r"\b(?:madad|sahayata) ke liye (?:shukriya|dhanyavad|dhanyawad)\b",
)

_OPT_OUT_RE = _rx(
    r"\bunsubscribe\w*", r"\bopt(?:ing)? ?out\b", r"\bnot (?:at all )?interest(?:ed|ing)?\b", r"\bnot intrested\b",
    r"\bno interest\b",
    r"\b(?:dont|do not|never|pls dont|please dont) (?:message|msg|text|contact|call|send|disturb|bother|ping|spam"
    r"|whatsapp|write)\b",
    r"\bstop (?:messag|msg|send|text|contact|call|spam|bother|ping|writ|disturb|whatsapp)\w*",
    r"\bleave me alone\b", r"\bremove (?:me|my (?:number|name|contact))\b", r"\bdelete my (?:number|contact|data)\b",
    r"\bno more (?:messages|msgs|texts|whatsapp|of this)\b", r"\bspam\w*", r"\bjunk messages?\b",
    r"\b(?:will|ll|going to) (?:block|report)\b", r"\bblock(?:ing)? (?:you|this|your)\b",
    r"\bdont want (?:these|this|your|any) (?:messages|msgs|texts|service|updates)\b",
    r"\bband kar(?:o|do| do| dijiye| dein)?\b", r"\bband kijiye\b", r"\b(?:messages?|msgs?) band\b",
    r"\bmat bhej\w*", r"\b(?:message|msg|messages) mat\b", r"\b(?:nahi|nahin|nhi) chahiye\b",
    r"\binterest(?:ed)? (?:nahi|nahin|nhi)\b", r"\bbother mat\b", r"\bpareshan mat\b", r"\btang mat\b",
    r"\bdobara mat\b",
    _dv("बंद करो"), _dv("बंद कर दो"), "मत भेज", "नहीं चाहिए", "रुचि नहीं", "परेशान मत",
)
_STOP_RE = re.compile(r"\bstop\b")
_STOP_OK_RE = re.compile(
    r"\b(?:stop (?:by|over|in|at|near|using|worrying)|bus stop|non ?stop|dont stop|do not stop|never stop|one stop"
    r"|cant stop|cannot stop|can not stop|wont stop)\b")

_HOSTILE_RE = _rx(
    r"\buseless\b", r"\bidiot\w*", r"\bstupid\b", r"\bnonsense\b", r"\brubbish\b", r"\bbakwa+s\b", r"\bbekaa?r\b",
    r"\bfraud\w*", r"\bscam\w*", r"\bcheat(?:er|ers|ing)?\b", r"\bfool(?:ish)?\b", r"\bpathetic\b", r"\bworst\b",
    r"\bdisgusting\b", r"\bshut up\b", r"\bget lost\b", r"\bwaste of (?:my )?time\b", r"\bbother(?:ing)? me\b",
    r"\bharass\w*", r"\bannoying\b", r"\bhate (?:you|this|these)\b", r"\bf+u+c+k\w*", r"\bshit\w*", r"\bbullshit\b",
    r"\bbloody\b", r"\bbastard\w*", r"\bcrap\b", r"\bwtf\b", r"\bdamn\b", r"\bchutiy\w*", r"\bbhenchod\b",
    r"\bmadarchod\b", r"\bgaa?ndu\b", r"\bkamine?\b", r"\bharami\b", r"\bullu\b", r"\bfaa?ltu\b", r"\bghatiya\b",
    r"\bdimag (?:mat )?kharab\b", r"\bpagal\b",
    _dv("बकवास"), _dv("बेकार"), _dv("फालतू"), "धोखा", _dv("पागल"), _dv("घटिया"),
)

_GRATITUDE = (r"thanks?|thank you|thanku|thankyou|thnx|thx|ty|tysm|shukriya|dhanyavad|dhanyawad|great|awesome|nice"
              r"|cool|perfect|super|wonderful|excellent|amazing|lovely|badhiya|bahut badhiya|mast")
_ACK = r"good|very good|noted|got it|ok|okay|okk|fine|sahi hai|theek hai|thik hai|done|alright|all right"
_FILLER = (r"a lot|so much|very much|ji|vera|bhai|sir|madam|mam|maam|again|dear|you|for this|for that|for the help"
           r"|for the update|for sharing|so|very|bahut")
_THANKS_ONLY_RE = re.compile(rf"^(?:{_GRATITUDE}|{_ACK}|{_FILLER})(?: (?:{_GRATITUDE}|{_ACK}|{_FILLER}))*$")
_GRATITUDE_RE = re.compile(rf"\b(?:{_GRATITUDE})\b")
_THANKS_WORD_RE = re.compile(r"\b(?:thanks?|thank you|thanku|thankyou|thnx|thx|ty|tysm|shukriya|dhanyavad|dhanyawad)\b")
_THANKS_DV_RE = _rx("धन्यवाद", "शुक्रिया")

_WAIT_DEFER_RE = _rx(
    r"\blater\b", r"(?<!was )(?<!were )(?<!been )(?<!was very )\bbusy\b", r"\bnot (?:right )?now\b",
    r"\b(?:dont|do not) have (?:the |any )?time\b", r"\bno time\b", r"\bmaybe (?:after|next|some)\b",
    r"\bnot today\b", r"\bin (?:a )?meeting\b",
    r"\bremind me\b", r"\btalk (?:to you )?(?:later|tomorrow|tmrw|next)\b", r"\bget back to you\b",
    r"\bgive me (?:some |a )?(?:time|minute|min|moment|day|few|couple)\b",
    r"\blet me (?:think|check|see|discuss|ask)\b",
    r"\bwill (?:think|check|discuss|see) (?:and|about)\b", r"\bdriving\b", r"\bout of (?:station|town)\b",
    r"\btravell?ing\b", r"\bon leave\b", r"\bafter (?:some time|sometime|a while)\b", r"\b(?:some )?other time\b",
    r"\banother time\b",
    r"\babhi (?:nahi|nahin|nhi|nai|busy|mat)\b", r"\bbaad (?:mein|me|main|mai)\b", r"\bthodi der\b",
    r"\bthoda (?:time|samay|ruk)\w*", r"\bsoch (?:ke|kar)\b", r"\bfursat\b", r"\bfree (?:ho ?ke|hokar|hone par)\b",
    r"\bbaat kar(?:te|enge|unga|ungi) hain?\b", r"\bbaat karenge\b", r"\bdekhte hain\b", r"\bdekhenge\b",
    _dv("बाद में"), _dv("अभी नहीं"), _dv("व्यस्त"), "सोच कर", "बात करते हैं",
)
_WAIT_TIME_RE = _rx(
    r"\btomorrow\b", r"\btmrw?\b", r"\bnext (?:week|month|monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b",
    r"\bkal\b", r"\bparso\b", r"\bagle (?:hafte|week|mahine|month)\b", r"\btonight\b", r"\bthis evening\b",
    r"\b(?:in|after) (?:\d+|a|an|one|two|three|few|couple of) ?(?:more )?(?:min|mins|minute|minutes|hour|hours|hr|hrs"
    r"|day|days|week|weeks)\b",
    r"\b\d+ (?:ghante|ghanta|minute|min|din) (?:baad|mein|me)\b", r"\bweekend\b", r"\bshaam ko\b",
    _dv("कल"), "अगले हफ्ते",
)

_DECLINE_STRONG_RE = _rx(
    r"\bno thanks?\b", r"\bno thank you\b", r"\bnot (?:needed|required|necessary|for me|for us|for now)\b",
    r"\b(?:dont|do not|dont really) (?:need|want)\b", r"\bno need\b",
    r"\balready (?:have|got|doing|done|using|running|posted|did|handled|sorted)\b",
    r"\b(?:we re|were|im|i am) good\b", r"\bill pass\b",
    r"\b(?:we|i) (?:dont|do not) (?:do|offer|provide|sell|stock|need) (?:that|this|it|these|those)\b",
    r"\bpass on this\b", r"\bnot this time\b",
    r"\bskip (?:it|this)\b", r"\bzaru?rat nahi\b", r"\bjaru?rat nahi\b", r"\bnahi karna\b", r"\bmat karo\b",
    r"\brehne do\b", r"\brahne do\b", r"\bnahi chahta\b", r"\bnahi chahti\b",
    _dv("ज़रूरत नहीं"), _dv("जरूरत नहीं"), "रहने दो",
)
_DECLINE_WEAK_RE = _rx(r"^(?:no|nope|nah|na|naa|nahi|nahin|nhi|nai|not really)\b", r"^नहीं")
_NOT_DECLINE_RE = _rx(
    r"\bno (?:problem|problems|worries|worry|issue|issues|doubt|probs|prob)\b", r"\bnot (?:a )?(?:problem|issue|bad)\b",
    r"\b(?:koi|kuch) (?:baat|dikkat|problem|issue|pareshani) (?:nahi|nahin|nhi)\b",
    r"\b(?:kyun|kyu|kyon) (?:nahi|nahin|nhi)\b", r"\bwhy not\b", r"\bnahi pata\b", r"\bpata nahi\b",
)

_ACCEPT_STRONG_RE = _rx(
    r"\bgo ahead\b", r"\blets (?:do it|do this|go|start|begin|proceed|try)\b", r"\b(?:do|start) it\b",
    r"\b(?:please|pls|plz) do\b", r"\bsend (?:it|me|over|the|them|this|that|across|now)\b",
    r"\bshare (?:it|the|them|this|that|now)\b", r"\bconfirm(?:ed)?\b", r"\bproceed\b",
    r"\bi want (?:to )?(?:join|it|this|that|in)\b", r"\bwant to join\b", r"\b(?:sign|signing) (?:me )?up\b",
    r"\bcount me in\b", r"\bim in\b", r"\bbook (?:it|me|this|that|the)\b", r"\bsounds (?:good|great|perfect|fine)\b",
    r"\blooks (?:good|great|perfect|fine)\b", r"\bwhats next\b", r"\bwhat next\b", r"\bnext steps?\b",
    r"\bgo for it\b", r"\bdo (?:that|this)\b", r"\bwhy not\b", r"\bof course\b", r"\bdefinitely\b", r"\babsolutely\b",
    r"\byes (?:please|pls|plz)\b", r"\bsure thing\b",
    r"\bkaro\b", r"\bkar (?:do|dijiye|dena|dein|lo|lijiye|de)\b", r"\bkardo\b", r"\bkarwa do\b",
    r"\bbhej (?:do|dijiye|dena|dein|de)\b", r"\bbhejo\b", r"\bbana (?:do|dijiye|dein|de)\b", r"\bbanao\b",
    r"\blikh (?:do|dijiye|dein)\b", r"\bdaal do\b", r"\bchalega\b", r"\bchalo\b",
    r"\b(?:kyun|kyu|kyon) (?:nahi|nahin|nhi)\b",
    r"\bbilkul\b", r"\bzaroor\b", r"\bjaroor\b", r"\bshuru (?:karo|kar do|karte|karein|kijiye)\b",
    r"\bjud(?:na|rna|ne|ungi|unga)\b", r"\bjodna\b", r"\bjoin (?:karna|karunga|karungi|kar)\b",
    r"^(?:please |pls |plz |kindly )?(?:draft|write|make|create|prepare|publish|post|schedule|share|send|book|start"
    r"|set ?up|run|launch|add)\b",
    r"\binterested\b",
    r"\bwhat (?:would|will) (?:it|this|that|the \w+) (?:look like|say)\b", r"\bhow (?:would|will) it look\b",
    r"\b(?:show me|can i see|let me see|send (?:me )?a sample)\b", r"\bkaisa dikhega\b", r"\bdikhao\b",
    _dv("करो"), _dv("कर दो"), _dv("भेज दो"), _dv("भेजो"), _dv("चलेगा"), _dv("ज़रूर"), _dv("जरूर"), _dv("बिल्कुल"),
    "जुड़ना",
)
_ACCEPT_WEAK_RE = _rx(
    r"\byes\b", r"\byess+\b", r"\byeah\b", r"\byea\b", r"\byep\b", r"\byup\b", r"\bsure\b", r"\bok\b", r"\bokay\b",
    r"\bokk+\b", r"\bokie\b", r"\bokey\b", r"\bkk\b", r"\balright\b", r"\ball right\b", r"\bfine\b", r"\bagreed?\b",
    r"\bdone\b", r"\bgreat\b", r"\bperfect\b", r"\bgood idea\b", r"\bnice\b",
    r"\bhaa?n\b", r"\bhaan ?ji\b", r"\bhanji\b", r"\bji haa?n\b", r"\btheek\b", r"\bthik\b",
    r"\bacc?ha\b", r"\bachha\b",
    r"^(?:k|ya|yaa|ha|haa|ji|jee|please|pls|plz)$",
    "हाँ", "हां", _dv("ठीक है"), _dv("अच्छा"),
)

_Q_START_RE = re.compile(
    r"^(?:what|whats|how|hows|why|when|where|which|who|whom|whose|kya|kaise|kaisa|kaisi|kitna|kitne|kitni|kab|kyun"
    r"|kyu|kyon|kaun|kaunsa|kaunsi|kahan|kidhar|konsa|konsi)\b"
    r"|^(?:can|could|will|would|should|shall|may|do|does|did|is|are|was|were|have|has)"
    r" (?:you|i|we|it|this|that|there|they|he|she|my|the|your)\b")
_Q_ANY_RE = _rx(
    r"\b(?:kya|kaise|kitna|kitne|kitni|kab|kyun|kyu|kaun|kahan|kaunsa|konsa)\b", r"\bhow (?:much|many|long|does|do)\b",
    r"\bwhat (?:is|are|about)\b", r"\bwhats the\b", r"\btell me (?:more|about|the)\b", r"\bexplain\b",
    r"\b(?:price|pricing|cost|charges?|fees?)\b",
    "क्या", "कैसे", "कितना", "कितने", _dv("कब"), "क्यों", "कौन",
)
_ACCEPT_Q_RE = _rx(
    r"\bwhats next\b", r"\bwhat next\b", r"\bwhat (?:do|should) (?:i|we) do (?:next|now)\b",
    r"\bwhat are the next steps\b", r"\b(?:when|how) (?:can|do|shall|should) we (?:start|begin|proceed)\b",
    r"\bhow (?:do|shall|should|can) (?:we|i) proceed\b",
    r"\b(?:can|could|will|would) you (?:please )?(?:send|share|show|do|draft|start|make|prepare|set|book|publish"
    r"|post|go ahead|write)\b",
    r"\bshall (?:we|i) (?:start|begin|proceed|go ahead|confirm)\b", r"\bcan we (?:start|begin|proceed|do it)\b",
    r"\b(?:ab|aage) kya\b", r"\bkab (?:se )?shuru\b", r"\bkya karna (?:hai|hoga|padega)\b",
    r"\b(?:kyun|kyu|kyon) (?:nahi|nahin|nhi)\b", r"\bwhy not\b",
    r"\bwhat (?:would|will) (?:it|this|that|the \w+) (?:look like|say)\b", r"\bhow (?:would|will) it look\b",
    r"\b(?:show me|can i see|let me see|send (?:me )?a sample)\b", r"\bkaisa dikhega\b", r"\bdikhao\b",
)

_QTYPES: list[tuple[str, re.Pattern]] = [
    ("call", _rx(r"\bcall me\b", r"\bgive me a call\b",
                 r"\b(?:can|could) (?:you|we) (?:call|talk on the phone|speak)\b",
                 r"\bphone (?:call|pe baat)\b", r"\bcall (?:karo|kar do|kijiye|karna)\b")),
    ("identity", _rx(r"\bwho gave you my number\b", r"\bhow did you get my number\b",
                     r"\bwho (?:are you|is this|r u)\b", r"\bwhos this\b", r"\bkaun (?:ho|hai|bol)\b",
                     r"\bare you (?:a |an )?(?:bot|human|real|robot|ai|person)\b", r"\bwhat is (?:vera|magicpin)\b",
                     r"\bwhats (?:vera|magicpin)\b", r"\btum kaun\b", r"\baap kaun\b")),
    ("audience", _rx(r"\bwhich (?:patients|clients|customers|members|people)\b",
                     r"\bwho (?:is|are) (?:it|this|these) for\b",
                     r"\bapplies? to\b", r"\brelevant (?:to|for)\b", r"\bkis(?:ke)? liye\b",
                     r"\bkaun se (?:patients|customers|clients|members|log)\b")),
    ("price", _rx(r"\b(?:price|pricing|cost|costs|charge|charges|fee|fees|rate|rates|how much|kitna|kitne ka|kitne ki"
                  r"|paisa|paise|amount|rupees|budget|expensive|free)\b", r"₹", r"\brs\b", "कितना", "कीमत")),
    ("count", _rx(r"\bhow many\b", r"\bkitne (?:log|patients|customers|clients|members|logon|patient|customer)\b",
                  r"\bnumber of\b", r"\bkitne\b")),
    ("source", _rx(r"\bsource\b", r"\bwhere (?:did|does|is) (?:this|that|it)\b", r"\bkahan se\b", r"\bproof\b",
                   r"\bstudy\b", r"\breference\b", r"\bwhich (?:study|paper|journal|report)\b", r"\bwho said\b",
                   r"\bdata from\b", r"\bhow do you know\b")),
    ("when", _rx(r"\bwhen\b", r"\bkab\b", r"\bwhat time\b", r"\bwhich (?:date|day)\b", r"\bdate\b", r"\bdeadline\b",
                 r"\btill when\b", r"\bhow long\b", r"\bkitne din\b", r"\btimings?\b", _dv("कब"))),
    ("why", _rx(r"\bwhy\b", r"\bkyun\b", r"\bkyu\b", r"\bkyon\b", r"\breason\b", "क्यों")),
    ("how", _rx(r"\bhow\b", r"\bkaise\b", r"\bprocess\b", r"\bsteps\b", r"\bprocedure\b", "कैसे")),
]

_GST_PRICE_RE = re.compile(
    r"\b(?:incl\w*|excl\w*|plus|extra|with|without|including|excluding)(?:\s+of)?\s+gst\b"
    r"|\bgst\s+(?:incl\w*|excl\w*|extra|included|charged|lagega|lagta|laga|hai kya|applicable)\b"
    r"|\b(?:price|amount|renewal|plan|fee|fees|charge|charges|invoice|cost|rate|subscription)\b.{0,40}\bgst\b"
    r"|\bgst\b.{0,40}\b(?:price|amount|renewal|plan|fee|fees|charge|charges|invoice|cost|rate|subscription)\b")
_GST_FILING_RE = re.compile(r"\b(?:file|filing|return|returns|registration|register|bharna|bharni)\b")
_OFF_TOPIC: list[tuple[str, str, re.Pattern]] = [
    ("ca", "GST filing", re.compile(r"\bgst\b.{0,24}\b(?:file|filing|return|returns|registration|register|bharna"
                                    r"|bharni|karna|help)\b|\b(?:file|filing|fill|bharna)\b.{0,24}\bgst\b")),
    ("ca", "GST", re.compile(r"\bgst\b")),
    ("ca", "Income-tax filing",
     re.compile(r"\b(?:itr|income ?tax|tax (?:return|filing|file|notice)|tds|advance tax)\b")),
    ("ca", "Accounts and bookkeeping", re.compile(r"\b(?:bookkeeping|balance sheet|tally|chartered accountant"
                                                  r"|audit report)\b")),
    ("bank", "A loan", re.compile(r"\b(?:loan|loans|emi|mudra|overdraft|cibil|credit score)\b")),
    ("bank", "That banking query", re.compile(r"\b(?:bank account|credit card|debit card|net ?banking)\b")),
    ("lawyer", "That legal matter", re.compile(r"\b(?:legal|lawyer|advocate|court|vakil|lawsuit|police|fir|trademark"
                                               r"|rent agreement|lease agreement)\b")),
    ("utility", "The electricity bill", re.compile(r"\b(?:electricity|bijli|light bill|power cut)\b")),
    ("utility", "That bill", re.compile(r"\b(?:water bill|gas (?:bill|connection)|phone bill|mobile recharge)\b")),
    ("it", "That tech issue", re.compile(r"\b(?:laptop|computer|printer|wifi|wi fi|router|internet connection"
                                         r"|broadband|pc repair|phone repair|mobile repair|antivirus)\b")),
    ("personal", "That", re.compile(r"\b(?:visa|passport|train ticket|flight ticket|movie tickets?|homework"
                                    r"|school admission|college admission|cricket score|stock tips|share market"
                                    r"|crypto)\b")),
]

_EDIT_RE = _rx(
    r"\b(?:change|edit|modify|tweak|replace|instead|shorter|longer|shorten|simplify|simpler|remove|delete|add"
    r"|include|mention|rewrite|reword|rephrase|correct|fix|make it|make the)\b",
    r"\b(?:badal\w*|hata\w*|jod\w*|chhota|chota|lamba|kam kar\w*|zyada kar\w*)\b",
)

_ORDINALS = {"first": 0, "1st": 0, "pehla": 0, "pehle": 0, "pahla": 0, "pehli": 0, "second": 1, "2nd": 1, "doosra": 1,
             "dusra": 1, "dusre": 1, "doosre": 1, "dusri": 1, "third": 2, "3rd": 2, "teesra": 2, "tisra": 2}
_DAYS = {
    "mon": ("mon", "monday", "somvar", "somwar"), "tue": ("tue", "tues", "tuesday", "mangal", "mangalvar"),
    "wed": ("wed", "wednesday", "budh", "budhvar", "budhwar"), "thu": ("thu", "thur", "thurs", "thursday", "guruvar"),
    "fri": ("fri", "friday", "shukravar", "shukrawar"), "sat": ("sat", "saturday", "shanivar", "shaniwar"),
    "sun": ("sun", "sunday", "ravivar", "raviwar", "itwar"),
}
_NUM_WORDS = {"a": 1, "an": 1, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5, "six": 6, "ten": 10,
              "few": 3, "couple of": 2, "ek": 1, "do": 2, "teen": 3, "char": 4, "chaar": 4, "paanch": 5, "panch": 5}
_UNIT_S = {"min": 60, "mins": 60, "minute": 60, "minutes": 60, "hour": 3600, "hours": 3600, "hr": 3600, "hrs": 3600,
           "ghante": 3600, "ghanta": 3600, "day": 86400, "days": 86400, "din": 86400, "week": 604800,
           "weeks": 604800, "hafte": 604800, "hafta": 604800}
_DURATION_RE = re.compile(
    r"\b(\d+(?:\.\d+)?|a|an|one|two|three|four|five|six|ten|few|couple of|ek|do|teen|char|chaar|paanch|panch)"
    r" ?(?:more )?(mins?|minutes?|hours?|hrs?|ghante|ghanta|days?|din|weeks?|hafte|hafta)\b")


# --------------------------------------------------------------------------- intent


@dataclass
class Intent:
    label: str                         # auto_reply | opt_out | hostile | thanks_close | slot_choice | wait_request
                                       # edit | decline | accept | off_topic | question | engaged | other
    confidence: float = 0.5
    details: dict[str, Any] = field(default_factory=dict)


def parse_wait_seconds(text: str) -> int:
    """How long the merchant asked us to wait, in seconds (default 30 minutes)."""
    norm = normalize_text(text)
    secs: float | None = None
    m = _DURATION_RE.search(norm)
    if re.search(r"\b(?:half an hour|aadha ghanta|adha ghanta)\b", norm):
        secs = 1800
    elif m:
        qty_raw, unit = m.group(1), m.group(2)
        qty = _NUM_WORDS.get(qty_raw)
        if qty is None:
            try:
                qty = float(qty_raw)
            except ValueError:
                qty = 1
        secs = qty * _UNIT_S.get(unit, 3600)
    elif re.search(r"\b(?:day after tomorrow|parso)\b", norm):
        secs = 2 * 86400
    elif re.search(r"\b(?:next month|agle mahine|agle month)\b", norm):
        secs = 30 * 86400
    elif re.search(r"\b(?:next week|agle hafte|agle week|next (?:monday|tuesday|wednesday|thursday|friday|saturday"
                   r"|sunday))\b", norm) or "अगले हफ्ते" in norm:
        secs = 7 * 86400
    elif re.search(r"\bweekend\b", norm):
        secs = 2 * 86400
    elif re.search(r"\b(?:tomorrow|tmrw?|kal|not today|aaj nahi)\b", norm) or re.search(_dv("कल"), norm):
        secs = 86400
    elif re.search(r"\b(?:tonight|this evening|evening|shaam|raat)\b", norm):
        secs = 4 * 3600
    elif re.search(r"\b(?:afternoon|dopahar)\b", norm):
        secs = 3 * 3600
    if secs is None:
        secs = DEFAULT_WAIT_S
    return int(max(MIN_WAIT_S, min(MAX_WAIT_S, secs)))


def _split_sentences(raw: str) -> list[tuple[str, bool]]:
    """[(normalised sentence, ended_with_question_mark)]."""
    out: list[tuple[str, bool]] = []
    for m in re.finditer(r"[^.!?\n।]+[.!?\n।]*", raw or ""):
        chunk = m.group(0)
        norm = normalize_text(chunk)
        if norm:
            out.append((norm, "?" in chunk))
    return out


def _genuine_question(raw: str) -> str:
    """The first real question in the message (not "what's next?" style commitments), normalised."""
    for sent, qmark in _split_sentences(raw):
        is_q = qmark or bool(_Q_START_RE.search(sent)) or bool(_Q_ANY_RE.search(sent))
        if is_q and not _ACCEPT_Q_RE.search(sent):
            return sent
    return ""


def question_type(text: str) -> str:
    norm = normalize_text(text)
    low = (text or "").lower()
    for qtype, rx in _QTYPES:
        if rx.search(norm) or (qtype == "price" and "₹" in low):
            return qtype
    return "details"


def _off_topic(norm: str, kind: str = "") -> tuple[str, str] | None:
    for area, thing, rx in _OFF_TOPIC:
        if not rx.search(norm):
            continue
        if thing in ("GST", "GST filing") and _GST_PRICE_RE.search(norm) and not _GST_FILING_RE.search(norm):
            continue                           # "is it inclusive of GST?" is a pricing question
        if area == "lawyer" and kind in ("regulation_change", "supply_alert"):
            continue                           # legal questions about a compliance item are on-topic
        return area, thing
    return None


def _slot_choice(raw: str, norm: str, slots: list[str]) -> int | None:
    if not slots:
        return None
    m = re.fullmatch(r"(?:option |slot |number |no |choice )?([1-9])(?: (?:please|pls|plz|works|chalega|theek hai|ok"
                     r"|okay|done|confirm|wala|vala|is fine|fine|good))*", norm)
    if m:
        idx = int(m.group(1)) - 1
        return idx if idx < len(slots) else None
    words = norm.split()
    for w in words:
        if w in _ORDINALS and _ORDINALS[w] < len(slots) and len(words) <= 8:
            return _ORDINALS[w]
    labels = [s.lower() for s in slots]
    hits: set[int] = set()
    for key, names in _DAYS.items():
        if any(n in words for n in names):
            hits |= {i for i, lab in enumerate(labels) if re.match(rf"\W*{key}", lab) or re.search(rf"\b{key}\w*", lab)}
    for clock in re.findall(r"\b(\d{1,2})(?::(\d{2}))? ?(am|pm)\b", (raw or "").lower()):
        hour, minute, ampm = clock
        pat = rf"\b{int(hour)}(?::{minute or '00'})? ?{ampm}\b" if minute else rf"\b{int(hour)}(?::00)? ?{ampm}\b"
        hits |= {i for i, lab in enumerate(labels) if re.search(pat, lab)}
    if len(hits) == 1:
        return hits.pop()
    return None


def classify_inbound(text: str, conv: Conversation | None, merchant_state: MerchantState | None) -> Intent:
    """Deterministic intent for one inbound message. Ordered rules; the first match wins."""
    raw = text if isinstance(text, str) else ("" if text is None else str(text))
    norm = normalize_text(raw)
    stage = conv.stage if conv is not None else "opened"
    kind = conv.kind if conv is not None else ""
    slots = list((conv.meta.get("slots") if conv is not None else None) or [])
    emoji_pos = any(ch in raw for ch in _POSITIVE_EMOJI)
    if not norm:
        if emoji_pos:
            return Intent("thanks_close" if stage in ("action", "done") else "accept", 0.6,
                          {"strength": "weak", "emoji": True})
        return Intent("other", 0.2, {"empty": True})

    opt_out = bool(_OPT_OUT_RE.search(norm)) or (bool(_STOP_RE.search(norm)) and not _STOP_OK_RE.search(norm))
    hostile = bool(_HOSTILE_RE.search(norm))
    accept_strong = bool(_ACCEPT_STRONG_RE.search(norm))
    accept_weak = bool(_ACCEPT_WEAK_RE.search(norm))
    question = _genuine_question(raw)
    has_q = bool(question)

    defer = bool(_WAIT_DEFER_RE.search(norm))
    time_ref = bool(_WAIT_TIME_RE.search(norm))
    not_decline = bool(_NOT_DECLINE_RE.search(norm))
    decline_strong = bool(_DECLINE_STRONG_RE.search(norm)) and not not_decline
    decline_weak = bool(_DECLINE_WEAK_RE.search(norm)) and not not_decline

    # 1. auto-reply: canned phrasing, or the same longer text repeated (in this thread / by this merchant)
    #    with no intent of its own (a merchant may legitimately repeat "abhi nahi, kal baat karte hain")
    strong = _AUTO_STRONG_RE.findall(norm)
    weak = _AUTO_WEAK_RE.findall(norm)
    other_signal = opt_out or hostile or accept_strong or has_q
    any_intent = (opt_out or hostile or accept_strong or accept_weak or has_q or defer or time_ref or decline_strong
                  or decline_weak or bool(_STOP_RE.search(norm)))
    repeated = not any_intent and _is_repeat_text(norm, raw, conv, merchant_state)
    if strong or len(weak) >= 2 or (weak and not other_signal) or repeated:
        why = "canned phrasing" if (strong or weak) else "same text repeated"
        return Intent("auto_reply", 0.95 if strong or repeated else 0.75, {"why": why, "norm": norm})

    # 2. explicit opt-out beats hostility; 3. hostility without a stop
    if opt_out:
        return Intent("opt_out", 0.95, {"hostile": hostile})
    if hostile:
        return Intent("hostile", 0.85, {})

    # 4. thanks after the task is delivered closes the conversation
    thanks_only = bool(_THANKS_ONLY_RE.match(norm)) and (bool(_GRATITUDE_RE.search(norm)) or emoji_pos)
    thanks_only = thanks_only or (bool(_THANKS_DV_RE.search(norm)) and len(norm.split()) <= 4)
    if thanks_only and "confirm" not in norm and stage in ("action", "done"):
        return Intent("thanks_close", 0.9, {})
    if stage == "done" and not has_q and (thanks_only or (accept_weak and len(norm.split()) <= 3)):
        return Intent("thanks_close", 0.7, {"ack": True})
    # plain "ok thanks" is an acknowledgement, not a commitment; a second one after our follow-up closes
    thanks_ack = thanks_only and (bool(_THANKS_WORD_RE.search(norm)) or bool(_THANKS_DV_RE.search(norm)))
    if thanks_ack and stage == "engaged":
        return Intent("thanks_close", 0.7, {"ack": True})
    if thanks_ack:
        return Intent("engaged", 0.6, {"ack": True})

    # 5. customer picks an offered slot
    slot_idx = _slot_choice(raw, norm, slots)
    if slot_idx is not None and not has_q:
        return Intent("slot_choice", 0.9, {"slot_index": slot_idx, "slot": slots[slot_idx]})

    # 6. wait request: deferral language, or a bare time reference without a commitment
    if defer or (time_ref and not accept_strong and not has_q):
        return Intent("wait_request", 0.85, {"wait_seconds": parse_wait_seconds(raw), "deferral": defer})

    # 7. feedback on a delivered draft
    if stage == "action" and _EDIT_RE.search(norm):
        return Intent("edit", 0.75, {})

    # 8. decline (no question attached)
    if not has_q and (decline_strong or decline_weak) and not accept_strong:
        return Intent("decline", 0.85 if decline_strong else 0.7, {})

    off = _off_topic(norm, kind)
    positive = accept_strong or accept_weak or emoji_pos
    # 9. commitment (a real question attached turns it into "answer, then proceed")
    if positive and not off:
        if has_q:
            return Intent("question", 0.8, {"qtype": question_type(question), "positive": True, "question": question})
        return Intent("accept", 0.9 if accept_strong else 0.75,
                      {"strength": "strong" if accept_strong else "weak", "stage": stage})
    # 10. off-topic ask; 11. question
    if off:
        return Intent("off_topic", 0.85, {"area": off[0], "thing": off[1], "positive": positive})
    if has_q:
        return Intent("question", 0.75, {"qtype": question_type(question), "question": question})
    topics = rt.extract_topics(raw)
    if topics:
        return Intent("accept", 0.7, {"strength": "implicit", "topics": topics})
    return Intent("engaged", 0.5, {"words": len(norm.split())})


def _is_repeat_text(norm: str, raw: str, conv: Conversation | None, mstate: MerchantState | None) -> bool:
    """Same longer text already received in this conversation, or 2+ times from this merchant overall."""
    if len(norm) < 20 or len(norm.split()) < 4:
        return False
    if conv is not None:
        prior = [t for t in conv.turns if t.role != "bot"]
        if prior and prior[-1].body == raw:
            prior = prior[:-1]                 # the engine appends the inbound turn before classifying
        if any(normalize_text(t.body) == norm for t in prior):
            return True
    if mstate is not None and mstate.auto_reply_texts.get(norm, 0) >= 1:
        return True
    return False


# --------------------------------------------------------------------------- lazy modules


def _module(name: str) -> Any:
    try:
        return importlib.import_module(name)
    except Exception:  # a missing / broken sibling must never break replies
        log.warning("module %s unavailable", name)
        return None


def _s(value: Any) -> str:
    return value.strip() if isinstance(value, str) else ("" if value is None else str(value).strip())


def _snippet(text: str, limit: int = 60) -> str:
    t = re.sub(r"\s+", " ", text or "").strip()
    return t if len(t) <= limit else t[: limit - 1].rstrip() + "…"


def _human_duration(secs: int) -> str:
    if secs % 604800 == 0:
        n = secs // 604800
        return f"{n} week{'s' if n > 1 else ''}"
    if secs % 86400 == 0:
        n = secs // 86400
        return "24 hours" if n == 1 else f"{n} days"
    if secs >= 3600 and secs % 3600 == 0:
        n = secs // 3600
        return f"{n} hour{'s' if n > 1 else ''}"
    return f"{max(1, secs // 60)} minutes"


def _norm_body(text: str) -> str:
    s = str(text or "").lower().replace("’", "'")
    s = re.sub(r"[^\w₹%]+", " ", s)
    return re.sub(r"\s+", " ", s).strip()


_ASK_RE = re.compile(
    r"(?:want me to(?: go ahead and)?|shall i|should i|reply yes and i(?:'|’)?ll|say yes and i(?:'|’)?ll"
    r"|just say (?:yes|go) and i(?:'|’)?ll)\s+([^?.!\n]{6,160})", re.IGNORECASE)


def extract_ask(body: str) -> str:
    """The offer made in an English opener ("Want me to draft 3 posts?" -> "draft 3 posts")."""
    matches = _ASK_RE.findall(body or "")
    if not matches:
        return ""
    ask = re.sub(r"\s+", " ", matches[-1]).strip(" ,;:-—")
    return ask if len(ask.split()) >= 2 else ""


# --------------------------------------------------------------------------- engine


@dataclass
class Decision:
    action: str                          # send | wait | end
    move: str                            # nudge, apology, action, confirm, answer, answer_action, slot, ...
    rationale: str = ""
    wait_seconds: int = 0
    end_reason: str = ""
    soft: bool = False


class ConversationEngine:
    """Rule-first multi-turn handler. One instance per process (state lives in the stores)."""

    def __init__(self, contexts: ContextStore, convs: ConversationStore, llm: Any = None) -> None:
        self.contexts = contexts
        self.convs = convs
        self.llm = llm

    # ------------------------------------------------------------------ opener registration

    def open_from_action(self, action: dict, composition: dict, now: str | None = None) -> None:
        """Store a tick opener as a conversation (idempotent) and append the opener bot turn."""
        action = action if isinstance(action, dict) else {}
        composition = composition if isinstance(composition, dict) else {}
        cid = _s(action.get("conversation_id"))
        if not cid:
            return
        meta = composition.get("meta") if isinstance(composition.get("meta"), dict) else {}
        body = _s(action.get("body") or composition.get("body"))
        trigger_id = _s(action.get("trigger_id") or meta.get("trigger_id")) or None
        kind = _s(meta.get("kind"))
        if not kind and trigger_id:
            trig = self.contexts.get("trigger", trigger_id)
            kind = _s((trig or {}).get("kind")) if isinstance(trig, dict) else ""
        self.convs.observe_time(now)
        fields = {
            "merchant_id": _s(action.get("merchant_id") or meta.get("merchant_id")) or None,
            "customer_id": _s(action.get("customer_id") or meta.get("customer_id")) or None,
            "trigger_id": trigger_id,
            "kind": kind,
            "send_as": _s(action.get("send_as") or composition.get("send_as")) or SEND_AS_VERA,
            "offer": _s(meta.get("offer")),
            "suppression_key": _s(action.get("suppression_key") or composition.get("suppression_key")),
            "language": _s(meta.get("language")),
            "facts_digest": [str(f) for f in (meta.get("facts") or []) if f][:8],
        }
        conv = self.convs.get(cid)
        if conv is None:
            conv = self.convs.create(cid, **fields)
        else:
            for key, value in fields.items():
                if value:
                    setattr(conv, key, value)
        conv.meta.update({
            "opener_cta": _s(action.get("cta") or composition.get("cta")),
            "template_name": _s(action.get("template_name") or composition.get("template_name")),
            "ask": extract_ask(body),
            "source": _s(meta.get("source")),
            "created_by": "tick",
        })
        if body and not any(t.role == "bot" for t in conv.turns):
            self.convs.add_turn(cid, "bot", body, ts=now, seq=next(_SEQ), move="opener",
                                cta=_s(action.get("cta") or composition.get("cta")))
        if not conv.inbound():
            conv.stage = "opened"
            conv.status = "active"

    # ------------------------------------------------------------------ reply

    async def handle_reply(self, req: dict) -> dict:
        """Next move for one inbound message. Never raises (except cancellation)."""
        started = time.monotonic()
        try:
            return await self._handle(req if isinstance(req, dict) else {}, started)
        except asyncio.CancelledError:
            raise
        except Exception:
            log.exception("handle_reply failed; using a safe fallback")
            return fallback_reply(req if isinstance(req, dict) else {})

    async def _handle(self, req: dict, started: float) -> dict:
        deadline = started + float(config.settings.reply_deadline_s)
        cid = _s(req.get("conversation_id")) or "conv_unknown"
        message = req.get("message")
        message = message if isinstance(message, str) else ("" if message is None else str(message))
        received = req.get("received_at") if isinstance(req.get("received_at"), str) else None
        self.convs.observe_time(received)
        now_iso = received if parse_iso(received) else (self.convs.sim_now or utc_now_iso())
        from_role = (_s(req.get("from_role")) or "merchant").lower()

        conv = self._get_or_create(cid, req, from_role, now_iso)
        role = "customer" if from_role == "customer" else "merchant"
        customer_facing = role == "customer" or bool(conv.customer_id) or conv.send_as == SEND_AS_MERCHANT
        mid = conv.merchant_id
        mstate = self.convs.merchant(mid) if mid else MerchantState(merchant_id="")

        self.convs.add_turn(cid, role, message, ts=now_iso, seq=next(_SEQ))
        inbound = conv.turns[-1] if conv.turns else None
        facts = self._facts(conv, customer_facing, now_iso)       # includes the inbound turn's numbers
        conv.meta["slots"] = list(facts.slots)

        intent = classify_inbound(message, conv, mstate)
        if inbound is not None:
            inbound.meta["intent"] = intent.label
        norm = normalize_text(message)
        if role == "merchant" and not customer_facing and len(norm.split()) >= 4:
            mstate.auto_reply_texts[norm] = mstate.auto_reply_texts.get(norm, 0) + 1

        decision = self._decide(conv, mstate, intent, message, customer_facing, req, now_iso)
        if decision.action == "wait":
            secs = int(decision.wait_seconds or DEFAULT_WAIT_S)
            conv.status = "waiting"
            base = parse_iso(now_iso)
            conv.wait_until = (base + timedelta(seconds=secs)).isoformat().replace("+00:00", "Z") if base else None
            return {"action": "wait", "wait_seconds": secs, "rationale": decision.rationale}
        if decision.action == "end":
            conv.status = "ended"
            conv.ended_reason = decision.end_reason or intent.label
            return {"action": "end", "rationale": decision.rationale}

        plan = self._language(conv, facts, message, customer_facing)
        body, cta, label, source = await self._write(conv, facts, intent, decision, message, customer_facing,
                                                     plan, mstate, deadline)
        self._after_send(conv, mstate, decision, intent, body, cta, label, source, plan, now_iso)
        rationale = self._send_rationale(decision, intent, message, label, source)
        return {"action": "send", "body": body, "cta": cta, "rationale": rationale}

    # ------------------------------------------------------------------ conversation lookup

    def _get_or_create(self, cid: str, req: dict, from_role: str, now_iso: str) -> Conversation:
        mid = _s(req.get("merchant_id")) or None
        cust = _s(req.get("customer_id")) or None
        conv = self.convs.get(cid)
        if conv is not None:
            if not conv.merchant_id and mid:
                conv.merchant_id = mid
            if not conv.customer_id and cust:
                conv.customer_id = cust
            return conv
        fields: dict[str, Any] = {
            "merchant_id": mid, "customer_id": cust, "kind": "unknown",
            "send_as": SEND_AS_MERCHANT if (cust or from_role == "customer") else SEND_AS_VERA,
        }
        parent = self._recent_parent(mid, cust, now_iso)
        if parent is not None:
            fields.update(kind=parent.kind or "unknown", offer=parent.offer, trigger_id=parent.trigger_id,
                          facts_digest=list(parent.facts_digest), language=parent.language,
                          customer_id=parent.customer_id)
        conv = self.convs.create(cid, **fields)
        conv.meta["created_by"] = "reply"
        if parent is not None:
            conv.meta["inherited_from"] = parent.conversation_id
            conv.meta["ask"] = parent.meta.get("ask", "")
        return conv

    def _recent_parent(self, mid: str | None, cust: str | None, now_iso: str) -> Conversation | None:
        """The merchant's latest tick-opened conversation (same audience), to give an unknown id context."""
        if not mid:
            return None
        now_dt = parse_iso(now_iso)
        best: Conversation | None = None
        for c in self.convs.for_merchant(mid):
            if c.meta.get("created_by") != "tick" or (c.customer_id or None) != (cust or None):
                continue
            ts = parse_iso(c.updated_at)
            if now_dt and ts and abs((now_dt - ts).total_seconds()) > 3 * 86400:
                continue
            if best is None or (c.updated_at or "") >= (best.updated_at or ""):
                best = c
        return best

    # ------------------------------------------------------------------ facts / language

    def _facts(self, conv: Conversation, customer_facing: bool, now_iso: str) -> FactSheet:
        merchant = self.contexts.get("merchant", conv.merchant_id) if conv.merchant_id else None
        turns = [{"from": "vera" if t.role == "bot" else t.role, "body": t.body, "ts": t.ts} for t in conv.turns]
        facts_mod = _module("app.facts")
        if not isinstance(merchant, dict) or facts_mod is None:
            sheet = FactSheet(kind=conv.kind or "", merchant_id=conv.merchant_id or "",
                              customer_id=conv.customer_id, scope="customer" if customer_facing else "merchant",
                              send_as=SEND_AS_MERCHANT if customer_facing else SEND_AS_VERA)
            sheet.allowed_numbers = _numbers_in(t["body"] for t in turns)
            return sheet
        trigger = self.contexts.get("trigger", conv.trigger_id) if conv.trigger_id else None
        if not isinstance(trigger, dict):
            known = conv.kind if conv.kind and conv.kind != "unknown" else ""
            trigger = {"id": "", "kind": known, "merchant_id": conv.merchant_id, "payload": {}} if known else {}
        customer = self.contexts.get("customer", conv.customer_id) if conv.customer_id else None
        category = self.contexts.category_for(merchant, trigger)
        try:
            sheet = facts_mod.build_facts(category, merchant, trigger, customer, now=now_iso, conversation_turns=turns)
        except Exception:
            log.exception("build_facts failed in reply")
            sheet = FactSheet(kind=conv.kind or "", merchant_id=conv.merchant_id or "")
        if customer_facing and sheet.scope != "customer":
            # customer context missing: never address the customer by the owner's name
            sheet.salutation = ""
            sheet.signer = sheet.signer or sheet.merchant_name
        return sheet

    def _language(self, conv: Conversation, facts: FactSheet, message: str, customer_facing: bool) -> LanguagePlan:
        lang_mod = _module("app.language")
        base = facts.language if isinstance(facts.language, LanguagePlan) else LanguagePlan()
        if conv.language and lang_mod is not None and conv.language != base.code:
            try:
                base = lang_mod.plan_for_code(conv.language)
            except Exception:
                pass
        if lang_mod is None:
            return base
        try:
            return lang_mod.plan_for_reply(base, message)
        except Exception:
            return base

    # ------------------------------------------------------------------ move selection

    def _decide(self, conv: Conversation, mstate: MerchantState, intent: Intent, message: str,
                customer_facing: bool, req: dict, now_iso: str) -> Decision:
        label = intent.label
        snip = _snippet(message)
        soft = False

        if label == "auto_reply":
            return self._auto_reply_move(conv, mstate, intent, message, customer_facing, now_iso)
        conv.auto_reply_streak = 0

        if conv.status == "ended":
            reopen = self._reopen_mode(conv, mstate, intent, customer_facing)
            if reopen is None:
                return Decision("end", "end", f"Conversation already closed ({conv.ended_reason or 'ended'}); "
                                              f"'{snip}' does not call for re-engaging, so staying quiet.",
                                end_reason=conv.ended_reason or "ended")
            conv.status = "active"
            conv.meta["reopened"] = int(conv.meta.get("reopened", 0)) + 1
            soft = reopen == "soft"
        elif conv.status == "waiting":
            conv.status = "active"

        if label == "opt_out":
            if customer_facing:
                conv.meta["customer_opted_out"] = True
                why = "Customer asked us to stop"
            else:
                mstate.opted_out = True
                mstate.opted_out_at = now_iso
                why = "Merchant explicitly opted out"
            return Decision("end", "end", f"{why} ('{snip}'). Closing the conversation and suppressing further "
                                          f"proactive messages.", end_reason="opt_out")

        if label == "hostile":
            conv.hostile_count += 1
            if not customer_facing:
                mstate.hostile_count += 1
            repeated = conv.hostile_count >= 2 or conv.meta.get("apologized")
            if repeated or (not customer_facing and mstate.hostile_count >= 3):
                return Decision("end", "end", f"Repeated frustration ('{snip}'); exiting gracefully without further "
                                              f"engagement.", end_reason="hostile")
            return Decision("send", "apology")

        if label == "thanks_close":
            return Decision("end", "end", f"Task delivered and acknowledged ('{snip}'); closing the conversation "
                                          f"without another ask.", end_reason="done")

        if label == "wait_request":
            secs = int(intent.details.get("wait_seconds") or DEFAULT_WAIT_S)
            return Decision("wait", "wait", f"Merchant asked for time ('{snip}'); backing off "
                                            f"{_human_duration(secs)} before following up.", wait_seconds=secs)

        if label == "decline":
            return Decision("end", "end", f"Declined ('{snip}'); closing politely without pushing the offer.",
                            end_reason="decline")

        if label == "slot_choice":
            return Decision("send", "slot", soft=soft)

        if soft:
            # re-opened after an opt-out / hostility: answer briefly, never pitch
            if label == "off_topic":
                return Decision("send", "off_topic", soft=True)
            if label == "question":
                return Decision("send", "answer", soft=True)

        if label == "edit":
            return Decision("send", "edit" if conv.stage == "action" else "action")

        if label == "accept":
            if customer_facing:
                held = str(conv.meta.get("artifact") or "")
                if conv.stage == "action" and held.startswith("held "):
                    # "CONFIRM" after we held a slot: book exactly that slot.
                    intent.details["slot"] = held[len("held "):]
                    return Decision("send", "slot")
                return Decision("send", "customer_accept")
            if conv.stage == "action":
                return Decision("send", "confirm")
            if conv.stage == "done":
                return Decision("end", "end", f"Task already completed; '{snip}' needs no further message.",
                                end_reason="done")
            return Decision("send", "action")

        if label == "question":
            if intent.details.get("positive") and not customer_facing and conv.stage not in ("action", "done"):
                return Decision("send", "answer_action")
            return Decision("send", "answer")

        if self._too_long(conv, req):
            return Decision("end", "end", "Conversation has run long without progress; closing gracefully instead "
                                          "of sending another nudge.", end_reason="max_turns")

        if label == "off_topic":
            conv.off_topic_count += 1
            return Decision("send", "off_topic", soft=conv.hostile_count > 0)

        # engaged / other
        if customer_facing and conv.stage == "done":
            return Decision("end", "end", f"Booking already confirmed; '{snip}' needs no further message.",
                            end_reason="done")
        if not customer_facing and conv.kind in ASK_KINDS and conv.stage in ("opened", "engaged") \
                and not intent.details.get("ack") and intent.details.get("words", 0) >= 1:
            return Decision("send", "action")      # they answered the question the opener asked
        return Decision("send", "continue")

    def _auto_reply_move(self, conv: Conversation, mstate: MerchantState, intent: Intent, message: str,
                         customer_facing: bool, now_iso: str) -> Decision:
        norm = normalize_text(message)
        conv_streak = self._streak([conv], norm)
        pool = [conv]
        if conv.merchant_id and not customer_facing:
            pool = [c for c in self.convs.for_merchant(conv.merchant_id) if not c.customer_id or c is conv]
        streak = max(conv_streak, self._streak(pool, norm))
        conv.auto_reply_streak = streak
        conv.auto_reply_total += 1
        snip = _snippet(message, 50)
        if customer_facing:
            if streak <= 1:
                return Decision("wait", "wait", f"Looks like an automated reply ('{snip}'); waiting a day for the "
                                                f"customer instead of replying to a bot.",
                                wait_seconds=AUTO_REPLY_WAIT_S)
            return Decision("end", "end", "Automated replies again; closing without further messages.",
                            end_reason="auto_reply")
        if streak <= 1 and conv.status != "ended":
            return Decision("send", "nudge")
        if streak == 2 and conv.status != "ended":
            return Decision("wait", "wait", f"Same auto-reply again (streak {streak}: '{snip}'); the owner is not at "
                                            f"the phone, so waiting 24 hours instead of burning turns.",
                            wait_seconds=AUTO_REPLY_WAIT_S)
        cooldown_min = int(config.settings.auto_reply_cooldown_min)
        base = parse_iso(now_iso)
        if mstate.merchant_id and base is not None:
            mstate.cooldown_until = (base + timedelta(minutes=cooldown_min)).isoformat().replace("+00:00", "Z")
        return Decision("end", "end", f"Auto-reply {max(streak, 3)} times in a row with no human response; closing "
                                      f"the conversation and pausing proactive sends to this merchant for "
                                      f"{cooldown_min} minutes.", end_reason="auto_reply")

    @staticmethod
    def _streak(pool: list[Conversation], norm: str) -> int:
        turns = [t for c in pool for t in c.turns if t.role != "bot" and "seq" in t.meta]
        turns.sort(key=lambda t: t.meta["seq"])
        streak = 0
        for t in reversed(turns):
            same = len(norm) >= 12 and normalize_text(t.body) == norm
            if t.meta.get("intent") == "auto_reply" or same:
                streak += 1
            else:
                break
        return max(1, streak)

    @staticmethod
    def _reopen_mode(conv: Conversation, mstate: MerchantState, intent: Intent, customer_facing: bool) -> str | None:
        """None: stay closed; "soft": answer briefly without pitching; "full": resume normally."""
        label = intent.label
        if label in ("opt_out", "hostile", "decline", "thanks_close", "wait_request", "auto_reply"):
            return None
        opted = conv.ended_reason in ("opt_out", "hostile") or conv.meta.get("customer_opted_out") or (
            mstate.opted_out and not customer_facing)
        if opted:
            if label in ("question", "off_topic"):
                return "soft"
            if label == "accept" and intent.details.get("strength") == "strong":
                if not customer_facing:
                    mstate.opted_out = False        # they explicitly asked us to go ahead again
                conv.meta.pop("customer_opted_out", None)
                return "full"
            return None
        if label in ("engaged", "other") and conv.ended_reason in ("done", "max_turns"):
            return None
        return "full"

    @staticmethod
    def _too_long(conv: Conversation, req: dict) -> bool:
        try:
            turn_no = int(req.get("turn_number") or 0)
        except (TypeError, ValueError):
            turn_no = 0
        inbound = len(conv.inbound())
        if max(inbound, turn_no // 2) > MAX_INBOUND_TURNS:
            return True
        progress_at = int(conv.meta.get("progress_bot_count", 0))
        return len(conv.bot_bodies()) - progress_at >= MAX_BOT_TURNS_WITHOUT_PROGRESS

    # ------------------------------------------------------------------ body

    def _reply_ctx(self, conv: Conversation, facts: FactSheet, intent: Intent, message: str,
                   customer_facing: bool, plan: LanguagePlan, soft: bool) -> rt.ReplyContext:
        lang = "hinglish" if plan.code in ("hinglish", "hi") else "en"
        kind = conv.kind if conv.kind and conv.kind != "unknown" else ""
        offer = self._offer(conv, facts, lang)
        topics = list(intent.details.get("topics") or rt.extract_topics(message))
        if not topics and kind in ASK_KINDS and intent.label == "engaged":
            topics = rt.extract_topics(message, loose=True)
        if not topics and not kind:
            last = next((h.get("body", "") for h in reversed(facts.history or [])
                         if h.get("from") == "merchant" and h.get("body") != message), "")
            topics = rt.extract_topics(last)
        return rt.ReplyContext(
            facts=facts, kind=kind, lang=lang, customer_facing=customer_facing, offer=offer, inbound=message,
            stage=conv.stage, variant=len(conv.bot_bodies()), topics=topics, soft=soft,
            artifact=str(conv.meta.get("artifact") or ""),
        )

    def _offer(self, conv: Conversation, facts: FactSheet, lang: str) -> str:
        """What the thread offered to do, as a verb phrase ("draft 3 Google posts")."""
        ask = str(conv.meta.get("ask") or "")
        if ask and lang == "en":
            return ask
        if conv.offer:
            return conv.offer
        # unknown thread: Vera's last offer in the merchant's history, else the most useful next step
        for h in reversed(facts.history or []):
            if h.get("from") == "vera":
                found = extract_ask(str(h.get("body") or ""))
                if found:
                    return found
                break
        view = rt.FactView(facts)
        if view.has("signal.stale_posts") or view.has("signal.no_recent_post"):
            return "draft a fresh Google post for you"
        if facts.offers_active:
            return f"draft a Google post for your {facts.offers_active[0]}"
        return ""

    async def _write(self, conv: Conversation, facts: FactSheet, intent: Intent, decision: Decision, message: str,
                     customer_facing: bool, plan: LanguagePlan, mstate: MerchantState,
                     deadline: float) -> tuple[str, str, str, str]:
        ctx = self._reply_ctx(conv, facts, intent, message, customer_facing, plan, decision.soft)
        prior = [b for b in conv.bot_bodies()] + list(mstate.sent_bodies)
        prior_norm = {_norm_body(b) for b in prior}
        reply = self._template(decision.move, ctx, intent)
        for _ in range(4):                      # anti-repetition: rotate wording before giving up
            if _norm_body(reply.body) not in prior_norm:
                break
            ctx.variant += 1
            reply = self._template(decision.move, ctx, intent)
        body, cta, label, source = reply.body, reply.cta, reply.label, "template"
        if _norm_body(body) in prior_norm:
            body = rt.distinct_variant(body, ctx, prior_norm)

        if decision.move in LLM_MOVES and not customer_facing and not decision.soft and self._llm_ready():
            cand = await self._llm_body(conv, facts, intent, decision, message, plan, body, cta, prior, deadline)
            if cand:
                body, source = cand, "llm"
        if cta not in CTA_VALUES:
            cta = CTA_OPEN_ENDED
        return body.strip(), cta, label, source

    def _template(self, move: str, ctx: rt.ReplyContext, intent: Intent) -> rt.Reply:
        d = intent.details
        if move == "nudge":
            return rt.auto_reply_nudge(ctx)
        if move == "apology":
            return rt.hostile_apology(ctx)
        if move == "off_topic":
            return rt.off_topic_redirect(ctx, str(d.get("area") or "personal"), str(d.get("thing") or "That"))
        if move == "answer":
            return rt.answer_question(ctx, str(d.get("qtype") or "details"))
        if move == "answer_action":
            return rt.answer_with_artifact(ctx, str(d.get("qtype") or "details"))
        if move == "action":
            return rt.action_artifact(ctx)
        if move == "confirm":
            return rt.confirm_done(ctx)
        if move == "edit":
            return rt.edit_ack(ctx)
        if move == "slot":
            slots = ctx.facts.slots
            idx = d.get("slot_index")
            slot = str(d.get("slot") or (slots[idx] if isinstance(idx, int) and idx < len(slots) else ""))
            return rt.slot_confirmation(ctx, slot) if slot else rt.slot_prompt(ctx)
        if move == "customer_accept":
            return rt.customer_accept(ctx)
        return rt.continue_thread(ctx)

    # ------------------------------------------------------------------ LLM path

    def _llm_ready(self) -> bool:
        llm = self.llm
        if llm is None or not callable(getattr(llm, "complete_json", None)):
            return False
        try:
            available = getattr(llm, "available", None)
            return bool(available()) if callable(available) else True
        except Exception:
            return False

    async def _llm_body(self, conv: Conversation, facts: FactSheet, intent: Intent, decision: Decision,
                        message: str, plan: LanguagePlan, baseline: str, cta: str, prior: list[str],
                        deadline: float) -> str | None:
        remaining = deadline - time.monotonic() - REPLY_MARGIN_S
        if remaining < MIN_LLM_S:
            return None
        timeout = min(remaining, float(config.settings.llm_timeout_s))
        system, user = reply_prompt(conv, facts, intent, decision.move, baseline, cta, plan, message)
        try:
            res = await asyncio.wait_for(
                self.llm.complete_json(system, user, schema=REPLY_SCHEMA, timeout=timeout,
                                       max_tokens=LLM_MAX_TOKENS, temperature=0.0),
                timeout=timeout + 0.3)
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            log.info("reply LLM unavailable (%s)", type(exc).__name__)
            return None
        body = res.get("body") if isinstance(res, dict) else None
        if not isinstance(body, str) or not body.strip():
            return None
        body = body.strip()
        mode = "reply_action" if decision.move in ("action", "answer_action", "edit") else "reply"
        issues = check_body(body, facts, prior_bodies=prior, mode=mode, customer_facing=False)
        if issues:
            log.info("reply LLM output rejected: %s", issues[:3])
            return None
        return body

    # ------------------------------------------------------------------ bookkeeping

    def _after_send(self, conv: Conversation, mstate: MerchantState, decision: Decision, intent: Intent, body: str,
                    cta: str, label: str, source: str, plan: LanguagePlan, now_iso: str) -> None:
        move = decision.move
        self.convs.add_turn(conv.conversation_id, "bot", body, ts=now_iso, seq=next(_SEQ), move=move, cta=cta,
                            intent=intent.label, source=source, label=label)
        if mstate.merchant_id:
            mstate.sent_bodies.append(body)
        conv.language = plan.code
        progress = False
        if move in ("action", "answer_action") or (move == "customer_accept" and cta == CTA_BINARY_CONFIRM):
            conv.stage = "action"
            conv.meta["artifact"] = label
            progress = True
        elif move in ("confirm", "slot") or (move == "customer_accept" and cta == CTA_NONE):
            conv.stage = "done"
            progress = True
            if move == "slot":
                conv.meta["booked_slot"] = intent.details.get("slot", "")
        elif move == "apology":
            conv.meta["apologized"] = True
        elif conv.stage == "opened" and move not in ("nudge",):
            conv.stage = "engaged"
        if progress:
            conv.meta["progress_bot_count"] = len(conv.bot_bodies())

    @staticmethod
    def _send_rationale(decision: Decision, intent: Intent, message: str, label: str, source: str) -> str:
        snip = _snippet(message)
        label = rt.artifact_label(label) if label in rt._ART_LABELS else label
        d = intent.details
        move = decision.move
        via = " (LLM wording, validated)" if source == "llm" else ""
        if move == "nudge":
            return (f"Detected a WhatsApp Business auto-reply ('{_snippet(message, 50)}'); one short owner-directed "
                    f"nudge with a single YES ask instead of repeating the pitch.")
        if move == "apology":
            return (f"Merchant is frustrated ('{snip}'); one-line apology with an explicit STOP path and no pitch. "
                    f"Will close if it continues.")
        if move == "off_topic":
            tail = "answered briefly without pitching" if decision.soft else "redirected to the thread's offer"
            return f"Out-of-scope ask ({d.get('thing') or 'unrelated'}) politely declined; {tail}.{via}"
        if move == "answer":
            if decision.soft:
                return f"Re-opened only to answer a genuine question ('{snip}') from known facts; no pitch.{via}"
            return (f"Answered the {d.get('qtype', 'details')} question ('{snip}') only from known facts, saying so "
                    f"where unknown; one clear next step.{via}")
        if move == "answer_action":
            return (f"Positive reply with a question ('{snip}'): answered it from known facts and moved straight to "
                    f"action with the {label or 'draft'}; one CONFIRM step.{via}")
        if move == "action":
            return (f"Merchant committed ('{snip}'); switched from pitch to ACTION mode and delivered the "
                    f"{label or 'draft'} grounded in their own data, with one CONFIRM-style next step.{via}")
        if move == "confirm":
            return f"Merchant confirmed ('{snip}'); reporting what is done and what happens next, no further ask."
        if move == "edit":
            return f"Merchant asked for a change ('{snip}'); acknowledged it and kept a single CONFIRM step.{via}"
        if move == "slot":
            return f"Customer picked {d.get('slot') or 'a slot'}; confirming the exact slot with a reschedule path."
        if move == "customer_accept":
            return f"Customer said yes ('{snip}'); moving straight to the booking step with the exact options we have."
        return (f"Engaged reply without a clear yes/no ('{snip}'); acknowledged it and offered the next concrete step "
                f"with a single ask.{via}")


# --------------------------------------------------------------------------- validation + prompt


def _numbers_in(texts: Any) -> set[str]:
    out: set[str] = set()
    for text in texts:
        for tok in extract_number_tokens(str(text or "")):
            n = normalize_number(tok)
            if n is not None:
                out.add(n)
    return out


def check_body(body: str, facts: FactSheet, *, prior_bodies: list[str] = (), mode: str = "reply",
               customer_facing: bool = False) -> list[str]:
    """Validator issues for a reply body (app.validator when present, else basic local checks)."""
    validator = _module("app.validator")
    if validator is not None and callable(getattr(validator, "validate_body", None)):
        try:
            return list(validator.validate_body(body, facts, prior_bodies=list(prior_bodies), mode=mode,
                                                customer_facing=customer_facing))
        except Exception:
            log.exception("validator failed on reply body")
    return _basic_issues(body, facts, list(prior_bodies), mode, customer_facing)


def _basic_issues(body: str, facts: FactSheet, prior: list[str], mode: str, customer_facing: bool) -> list[str]:
    issues: list[str] = []
    low = body.lower()
    if re.search(r"https?://|www\.|\.com\b|\.in\b", low):
        issues.append("url")
    if mode == "reply_action":
        if rt.has_qualifying(body):
            issues.append("qualifying")
        if not any(w in low for w in ("done", "sending", "draft", "here", "confirm", "proceed", "next")):
            issues.append("no_action_word")
    if customer_facing and re.search(r"\b(?:vera|magic\s?pin)\b", low):
        issues.append("brand_mention")
    allowed = facts.allowed_numbers or set()
    for tok in extract_number_tokens(body):
        n = normalize_number(tok)
        marked = any(ch in tok for ch in "%₹") or tok.lower().endswith("x")
        if n and n not in allowed and (marked or not (n.isdigit() and int(n) <= 10)):
            issues.append(f"ungrounded_number: {tok}")
    if any(_norm_body(p) == _norm_body(body) for p in prior):
        issues.append("repeat")
    return issues


_MOVE_BRIEF = {
    "action": "ACTION MODE. The merchant has committed. Deliver the actual artifact now (the drafts / summary / "
              "steps themselves, as in the baseline), say what happens next, and end with one 'Reply CONFIRM ...' "
              "line. Never ask a qualifying question.",
    "answer_action": "The merchant said yes AND asked a question. Answer the question in one line from the facts "
                     "(say you will check if it is not in the facts), then deliver the artifact and end with one "
                     "'Reply CONFIRM ...' line. Never ask a qualifying question.",
    "answer": "Answer the merchant's question using ONLY the facts. If the answer is not in the facts, say you will "
              "check (never guess). Then one short call to action, or none if the baseline has none.",
    "off_topic": "Politely decline the out-of-scope request in one line (say who is best placed to help), then bring "
                 "the conversation back to the thread's offer with one question.",
    "continue": "Acknowledge what the merchant said in a few words, add one relevant fact, and offer the next "
                "concrete step with one yes/no question.",
    "edit": "Acknowledge the requested change to the draft specifically, apply it, and end with one "
            "'Reply CONFIRM ...' line.",
}


def reply_prompt(conv: Conversation, facts: FactSheet, intent: Intent, move: str, baseline: str, cta: str,
                 plan: LanguagePlan, message: str) -> tuple[str, str]:
    """(system, user) prompt for rewriting one reply body."""
    limit = 900 if move in ("action", "answer_action", "edit") else 450
    system = (
        "You are Vera, magicpin's WhatsApp assistant for Indian local businesses (dentists, salons, restaurants, "
        "gyms, pharmacies). You are mid-conversation with a business owner. Write ONLY the next WhatsApp message.\n"
        "Rules:\n"
        "- Perform exactly the REQUIRED MOVE. Do not re-introduce yourself; no greetings or preambles.\n"
        "- Use only the facts provided. Never invent numbers, prices, dates, names, studies, reviews, slots or "
        "offers. Every number you write must appear in the facts, the offers or the conversation.\n"
        "- No URLs, no internal field names, no snake_case, never the words 'trigger' or 'payload'.\n"
        "- Exactly one call to action, in the last sentence. Keep the baseline's CTA type.\n"
        "- Never use the phrases 'would you', 'do you', 'can you tell', 'what if', 'how about'.\n"
        f"- Concise WhatsApp style, at most {limit} characters. Line breaks are fine for drafts.\n"
        f"- Language: {plan.instruction}\n"
        'Return JSON only: {"body": "<message>", "rationale": "<one sentence>"}'
    )
    turns = conv.turns[-TRANSCRIPT_TURNS:]
    who = "Customer" if conv.customer_id else "Merchant"
    transcript = "\n".join(f"{'Vera' if t.role == 'bot' else who}: {_snippet(t.body, 600)}" for t in turns)
    fact_lines = [f"- {f.text}" for f in facts.anchor_facts[:8]]
    fact_lines += [f"- {f.text}" for f in _prompt_support(facts)]
    fact_lines += [f"- {t}" for t in conv.facts_digest if f"- {t}" not in fact_lines][:6]
    user = "\n\n".join(p for p in [
        f"CONVERSATION (oldest first):\n{transcript}",
        f"THREAD: {rt.thread_topic(rt.ReplyContext(facts=facts, kind=conv.kind if conv.kind != 'unknown' else ''))}. "
        f"What Vera offered to do: {conv.meta.get('ask') or conv.offer or 'not recorded'}.",
        f"BUSINESS: {facts.merchant_name or 'unknown'}"
        f"{', ' + facts.locality if facts.locality else ''}; owner addressed as {facts.salutation or 'the owner'}; "
        f"category {facts.category_slug or 'unknown'}; tone {facts.voice_tone or 'warm, practical'}.",
        "FACTS YOU MAY USE:\n" + ("\n".join(fact_lines) if fact_lines else "- (none beyond the conversation)"),
        f"ACTIVE OFFERS (quote exactly): {'; '.join(facts.offers_active) or 'none'}",
        f"OPEN SLOTS (exact labels): {'; '.join(facts.slots)}" if facts.slots else "",
        ("JUDGMENT NOTES (never quote verbatim):\n" + "\n".join(f"- {n}" for n in facts.notes[:4]))
        if facts.notes else "",
        f"TABOO WORDS: {', '.join(facts.taboos) or 'none'}",
        f"DETECTED INTENT: {intent.label} ({', '.join(f'{k}={v}' for k, v in intent.details.items() if k != 'norm')})",
        f"REQUIRED MOVE: {_MOVE_BRIEF.get(move, _MOVE_BRIEF['continue'])} CTA type: {cta}.",
        "BASELINE REPLY (correct and grounded; improve specificity and flow, keep every fact and the same single "
        f"CTA; returning it unchanged is acceptable):\n{baseline}",
        f"MERCHANT'S LATEST MESSAGE: {message}",
    ] if p)
    return system, user


_SUPPORT_ORDER = ("agg", "offer", "review", "customer", "signal", "derived", "seasonal", "trend", "merchant", "perf")
_SUPPORT_CAPS = {"agg": 4, "offer": 3, "review": 2, "customer": 5, "signal": 3, "perf": 4, "merchant": 2}


def _prompt_support(facts: FactSheet, limit: int = 14) -> list:
    """Most useful support facts first (cohorts, offers, reviews) instead of a wall of perf numbers."""
    groups: dict[str, list] = {}
    for f in facts.support_facts:
        groups.setdefault(f.key.split(".")[0], []).append(f)
    out: list = []
    for g in _SUPPORT_ORDER:
        out.extend(groups.get(g, [])[: _SUPPORT_CAPS.get(g, 2)])
    return out[:limit]


def fallback_reply(req: dict) -> dict:
    """Last-resort reply when the engine itself fails: exit on a stop, act on a clear yes, else back off."""
    message = req.get("message") if isinstance(req, dict) else ""
    message = message if isinstance(message, str) else ""
    intent = classify_inbound(message, None, None)
    if intent.label in ("opt_out", "hostile", "decline", "auto_reply", "thanks_close"):
        return {"action": "end", "rationale": f"Closing politely ({intent.label.replace('_', ' ')} detected)."}
    if intent.label == "wait_request":
        return {"action": "wait", "wait_seconds": int(intent.details.get("wait_seconds") or DEFAULT_WAIT_S),
                "rationale": "Merchant asked for time; backing off."}
    if intent.label == "accept":
        return {"action": "send", "cta": CTA_BINARY_CONFIRM,
                "body": "Great, on it. I'm preparing the draft now and will share it here next. "
                        "Reply CONFIRM to proceed.",
                "rationale": "Merchant committed; moving straight to action with a single confirm."}
    return {"action": "wait", "wait_seconds": DEFAULT_WAIT_S,
            "rationale": "Could not compose a grounded reply; backing off 30 minutes rather than sending a generic "
                         "message."}


__all__ = [
    "Intent", "Decision", "ConversationEngine", "classify_inbound", "parse_wait_seconds", "normalize_text",
    "question_type", "extract_ask", "check_body", "reply_prompt", "fallback_reply",
]
